// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onkfxvjrumorofugrczp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ua2Z4dmpydW1vcm9mdWdyY3pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NjQ1NDcsImV4cCI6MjA2MDE0MDU0N30.y35rArex9qn8QkP6uHSIGObZKBe3zNNBKNN1_S630hE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);